### ISSUE TITLE
_obj fails to index global TEMP FIX

### ISSUE THREAD

**Issue by Timo2024** [ilrathCXV/ArtiGrok-Ballistics-GAMMA-ilrath-Mo3#2]
I'm using the rework repo

I changed it to just obj vs _obj, and it fixed my crashes when shooting explosive rounds… not sure not a scripting wizard yet, but I couldn't locate a global “_obj” and not sure if this breaks the intended effect or not

FROM THIS:
		level.iterate_nearest(bullet.position, frag_radius, function(_obj)
			if (IsStalker(_obj) or IsMonster(_obj)) and _obj:id() ~= AC_ID and _obj:id() ~= 65535 then
				if string.find(obj:name(), "legs") then return end -- First-person legs are being counted as an object
				if _obj:alive() then
					local npc_pos = _obj:position()
					local dist = npc_pos:distance_to(bullet.position)
					local blast_div_factor = ((blast_radius - (dist * 0.5)) / blast_radius) or 0
					blast_div_factor = clamp(blast_div_factor, 0, 1)
					local is_frag_hit = false
					local frag_hit_num = 0
					if total_frags > 0 then
						is_frag_hit = (frags_temp - total_frags) < math_random(total_frags, frags_temp)
						if is_frag_hit then
							frag_hit_num = math_random(1, total_frags) or 1
							total_frags = total_frags - frag_hit_num
						end
					end

					-- printf("[ArtiGrok - Exp] %s is hit with %s fragments (blast damage mod.: %s)", _obj and _obj:name(), frag_hit_num, blast_div_factor)

					local k_hit = ini_sys:r_float_ex(ammo_sec, "k_hit") or 1
					if k_hit < 1 then k_hit = 1 end

					local h = hit()
					h.type = (is_frag_hit and blast_div_factor < 0.3 and hit.fire_wound) or hit.explosion
					h.power = ((is_frag_hit and frag_power * frag_hit_num) or 0) + (blast_power * blast_div_factor)
					h.power = h.power * k_hit
					h.impulse = ((is_frag_hit and frag_impulse * frag_hit_num) or 0) + (blast_impulse * blast_div_factor)
					h.direction = VEC_Y
					h.bone = "bip01_spine"
					h.draftsman = db.actor
					h.weapon_id = explode_obj
					_obj:hit(h)
					explode_hits = explode_hits + 1
				end
			end
		end)

TO THIS:
		level.iterate_nearest(bullet.position, frag_radius, function(obj)
			if (IsStalker(obj) or IsMonster(obj)) and obj:id() ~= AC_ID and obj:id() ~= 65535 then
				if string.find(obj:name(), "legs") then return end -- First-person legs are being counted as an object
				if obj:alive() then
					local npc_pos = obj:position()
					local dist = npc_pos:distance_to(bullet.position)
					local blast_div_factor = ((blast_radius - (dist * 0.5)) / blast_radius) or 0
					blast_div_factor = clamp(blast_div_factor, 0, 1)
					local is_frag_hit = false
					local frag_hit_num = 0
					if total_frags > 0 then
						is_frag_hit = (frags_temp - total_frags) < math_random(total_frags, frags_temp)
						if is_frag_hit then
							frag_hit_num = math_random(1, total_frags) or 1
							total_frags = total_frags - frag_hit_num
						end
					end

					-- printf("[ArtiGrok - Exp] %s is hit with %s fragments (blast damage mod.: %s)", _obj and _obj:name(), frag_hit_num, blast_div_factor)

					local k_hit = ini_sys:r_float_ex(ammo_sec, "k_hit") or 1
					if k_hit < 1 then k_hit = 1 end

					local h = hit()
					h.type = (is_frag_hit and blast_div_factor < 0.3 and hit.fire_wound) or hit.explosion
					h.power = ((is_frag_hit and frag_power * frag_hit_num) or 0) + (blast_power * blast_div_factor)
					h.power = h.power * k_hit
					h.impulse = ((is_frag_hit and frag_impulse * frag_hit_num) or 0) + (blast_impulse * blast_div_factor)
					h.direction = VEC_Y
					h.bone = "bip01_spine"
					h.draftsman = db.actor
					h.weapon_id = explode_obj
					obj:hit(h)
					explode_hits = explode_hits + 1
				end
			end
		end)

**Comment by ilrathCXV** [comment]
Yes, I did catch that here recently. That has been fixed in the current Rework build. After a bit more development, I will push what I have for the Rework onto the live build for people to use.

**Comment by Timo2024** [comment]
Oh nice dude I know it's pre pre pre I also figured out the missing thens you fixed as well but I like cutting edge i'll close this thanks
